apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-account-config
  namespace: bank-account
data:
  application.properties: |
    server.port=8080
    spring.profiles.active=prod
    spring.datasource.url=jdbc:postgresql://postgres-service:5432/bankaccount
    spring.redis.host=redis-service
    spring.redis.port=6379
    management.endpoints.web.exposure.include=health,metrics,prometheus,info
    management.endpoint.health.show-details=when-authorized
    logging.level.io.artur.bankaccount=INFO