package io.artur.eventsourcing.events;

import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

class EventMetadataTest {

    @Test
    void createEventMetadataWithAllFields() {
        Map<String, String> additionalProps = Map.of("source", "test", "environment", "dev");
        EventMetadata metadata = new EventMetadata("correlation-123", "causation-456", "user-789",
                "TestApp/1.0", "192.168.1.1", 2, additionalProps);
        
        assertEquals("correlation-123", metadata.getCorrelationId());
        assertEquals("causation-456", metadata.getCausationId());
        assertEquals("user-789", metadata.getUserId());
        assertEquals("TestApp/1.0", metadata.getUserAgent());
        assertEquals("192.168.1.1", metadata.getIpAddress());
        assertEquals(2, metadata.getVersion());
        assertEquals(additionalProps, metadata.getAdditionalProperties());
        assertNotNull(metadata.getTimestamp());
        assertTrue(metadata.getTimestamp().isBefore(LocalDateTime.now().plusSeconds(1)));
    }

    @Test
    void createEventMetadataWithVersionOnly() {
        EventMetadata metadata = new EventMetadata(1);
        
        assertNotNull(metadata.getCorrelationId()); // Should be auto-generated
        assertNull(metadata.getCausationId());
        assertNull(metadata.getUserId());
        assertNull(metadata.getUserAgent());
        assertNull(metadata.getIpAddress());
        assertEquals(1, metadata.getVersion());
        assertTrue(metadata.getAdditionalProperties().isEmpty());
        assertNotNull(metadata.getTimestamp());
    }

    @Test
    void correlationIdAutoGenerated() {
        EventMetadata metadata1 = new EventMetadata(1);
        EventMetadata metadata2 = new EventMetadata(1);
        
        assertNotNull(metadata1.getCorrelationId());
        assertNotNull(metadata2.getCorrelationId());
        assertNotEquals(metadata1.getCorrelationId(), metadata2.getCorrelationId());
    }

    @Test
    void emptyAdditionalPropertiesWhenNull() {
        EventMetadata metadata = new EventMetadata("corr", null, null, null, null, 1, null);
        
        assertNotNull(metadata.getAdditionalProperties());
        assertTrue(metadata.getAdditionalProperties().isEmpty());
    }
}